### ISSUE TITLE
Add a new option for the slash

### ISSUE THREAD

**Issue by tuxkernel** [cspiel/typog#4]
![typoG](https://github.com/user-attachments/assets/2c2a63d2-cfec-4663-883a-158e06a6a910)

It's just a suggestion ;-)

**Comment by cspiel** [comment]
I like your idea for an extension of
`\kernedslash`.  BTW, your example is striking.

Currently, I see two possibilities.  One is your
suggestion of an additional package option
`raiseslash` and the other is additional,
optional arguments to the macros `\kernedslash`
and `\kernedslash*` similar to `\kernedhyphen`,
where we already have an optional `raise`
argument.  Both have their own merits.

If you raise or lower a slash, usually you'll
want to kern it.  If it is the other way around
not necessarily -- at least I think so.  Is just
raising the slash but not kerning it another
typical use case?

Optional arguments offer more flexibility.  And
you could define shortcuts like e.g.

```
\newcommand*{\raiseslash}{.05em}
\newcommand*{\raisedkernedslash}{\kernedslash[\raiseslash]\relax}
```

If however *every* `\kernedslash` always must
be raised or lowered, we don't need that much
flexibility and a package option does the job.

Your suggestions, preferences?

**Comment by tuxkernel** [comment]
I really was thinking in a new option `lowerslash=<dimen>` in the package. When you read the typog package documentation, almost all options are 'raised' (`\capitaldash`, `\capitalhyphen`, and`\capitaltimes`. The slash is one exception when you are using lowercases (`input/output`), but not in all caps (`INPUT/OUTPUT`), because `\kernedslash` add some kerning (before and after) and match very well. The problem with the slash in lowercases is, I think, ascenders and descenders. Similar problems arise with exclamation and interrogation marks (spanish), because we use two (in all caps):

![all-caps](https://github.com/user-attachments/assets/195c1e86-af63-4c0e-a7b5-ffb5a513d457)
